server:
  port: 8888

logging:
  path: logs/
  level:
    root: info

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2345free/itzone123-config-repo.git
          search-paths: weather
      profile: dev

